// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"
	domains "covid/internal/core/domains"

	mock "github.com/stretchr/testify/mock"
)

// CovidRepository is an autogenerated mock type for the CovidRepository type
type CovidRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, in
func (_m *CovidRepository) Create(ctx context.Context, in domains.CovidSummary) (*domains.CovidSummary, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domains.CovidSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domains.CovidSummary) (*domains.CovidSummary, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domains.CovidSummary) *domains.CovidSummary); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domains.CovidSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domains.CovidSummary) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCovidRepository creates a new instance of CovidRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCovidRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CovidRepository {
	mock := &CovidRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
