// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"
	dtos "covid/internal/dtos"

	mock "github.com/stretchr/testify/mock"
)

// CovidAdapter is an autogenerated mock type for the CovidAdapter type
type CovidAdapter struct {
	mock.Mock
}

// GetCovidRecords provides a mock function with given fields: ctx
func (_m *CovidAdapter) GetCovidRecords(ctx context.Context) (*dtos.CovidResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetCovidRecords")
	}

	var r0 *dtos.CovidResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*dtos.CovidResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *dtos.CovidResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.CovidResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCovidAdapter creates a new instance of CovidAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCovidAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *CovidAdapter {
	mock := &CovidAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
